import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import GlobalContextProvider, { GlobalContext } from '../context';
import './globals.css';
import { Josefin_Sans, Crimson_Text } from 'next/font/google';
import type { NavbarProps } from '../components/Navbar';

const josefin = Josefin_Sans({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-josefin',
});

const crimsontxt = Crimson_Text({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-crimsontxt',
  weight: ['400'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const navigationHeaders: NavbarProps = {
  mainHeaders: [
    { title: 'Bộ sưu tập mới', url: '/new-collection' },
    {
      title: 'Đồ ngủ',
      url: '/products/nightwear',
      subHeaders: [
        {
          title: '',
          url: '',
        },
      ],
    },
    {
      title: 'Đồ bơi',
      url: ' /products/swimwear',
      subHeaders: [
        {
          title: '',
          url: '',
        },
      ],
    },
    {
      title: 'Về chúng tôi',
      url: '/about-us',
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${josefin.variable} ${crimsontxt.variable}`}>
        <GlobalContextProvider>
          <Navbar mainHeaders={navigationHeaders.mainHeaders} />
          <Sidebar headers={navigationHeaders.mainHeaders} />
          <main>{children}</main>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
