import GlobalContextProvider from '../context';
import './globals.css';
import { Josefin_Sans, Crimson_Text } from 'next/font/google';

const josefin = Josefin_Sans({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-josefin',
});

const crimsontxt = Crimson_Text({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-crimsontxt',
  weight: ['400'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${josefin.variable} ${crimsontxt.variable}`}>
        <GlobalContextProvider>
          <main>{children}</main>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
