import Navbar from './components/NavBar';
import Sidebar from './components/SideBar';
import GlobalContextProvider from '../../context';
import './globals.css';
import { Josefin_Sans, Crimson_Text } from 'next/font/google';
import PromoBar from './components/PromoBar';
import { getStrapiGlobal } from './utils/strapi-api';
import { ClientGlobal } from '../../types/strapi';

const josefin = Josefin_Sans({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-josefin',
});

const crimsontxt = Crimson_Text({
  subsets: ['latin', 'vietnamese'],
  variable: '--font-crimsontxt',
  weight: ['400'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const globals: ClientGlobal = await getStrapiGlobal(params.lang);
  if (!globals.data) return null;

  const { navbar, footer } = globals.data.attributes;
  console.log(navbar);

  return (
    <html lang={params.lang}>
      <body className={`${josefin.variable} ${crimsontxt.variable}`}>
        <GlobalContextProvider>
          <PromoBar data={navbar.promobar} />
          <Navbar mainHeaders={navbar.mainHeaders} />
          <Sidebar headers={navbar.mainHeaders} />
          <main>{children}</main>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
